<?php

/**
 * Test class for Wootook_Object.
 * Generated by PHPUnit on 2011-09-01 at 11:24:52.
 */
class Test_Legacies_Core_LayoutTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Wootook_Object
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->markTestIncomplete();
        /*
        $layoutDir = vfsStreamWrapper::getContent('');
        vfsStream::addStructure(array());

        $this->_object = new Legacies_Core_Layout();
        */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testEmpty()
    {

    }
}
