<div class="install">
  <h1><?php echo $this->__('Welcome to the Wootook! installer')?></h1>
  <?php echo $this->getLayout()->getMessagesblock()->renderGroupedHtml()?>
  <p><?php echo $this->__('This page will guide you through the installation proces of Wootook! the MMO game engine platform.')?></p>
  <p><?php echo $this->__('Feel free to ask for help at any time at <a href="%s">wootook.org</a>.', 'http://wootook.org/board/')?></p>
  <p><button onclick="document.location.href='?mode=install&step=1'"><?php echo $this->__('Next step')?></button></p>
</div>