<?php

namespace Test\Wootook\Core\DateTime;

/**
* Test class for Wootook\Core\DateTime\DateTime.
* Generated by PHPUnit on 2011-09-01 at 11:24:
*/
class DateTimeTest extends \PHPUnit_Framework_TestCase
{
    public function testSupportsAdditionOfDays()
    {
        $date = new \Wootook\Core\DateTime\DateTime('2010-11-26');
        $date->add(new \DateInterval('P15D')); // Period of 15 Days
        $this->assertEquals('2010-12-11', $date->format('Y-m-d'));
    }

    public function testSupportsSubtractionOfMonths()
    {
        $date = new \DateTime('2010-11-26');
        $date->sub(new \DateInterval('P20M')); // Period of 15 Days
        $this->assertEquals('2009-03-26', $date->format('Y-m-d'));
    }

    // takes into account leap years, number of days of the month, etc.
    public function testSupportsDifferenceOfDates()
    {
        $stopDate = new \DateTime('2010-11-26');
        $startDate = new \DateTime('2010-10-28');
        $duration = $stopDate->diff($startDate);
        $this->assertEquals('29', $duration->format('%d'));
    }

    // never use mktime() again
    public function testSupportsAlsoTimeAndOperatorOverloading()
    {
        $datetime = new \DateTime('2010-11-26 12:00');
        $this->assertTrue($datetime > new \DateTime('2010-11-26 11:00'));
        $this->assertTrue($datetime == new \DateTime('2010-11-26 12:00'));
        $this->assertTrue($datetime < new \DateTime('2010-11-26 13:00'));
    }
}
