<div id="main">
<div id="login">
<div id="login_input">
<form name="formular" action="" method="post" onsubmit="changeAction('login');">
<table width="400" border="0" cellpadding="0" cellspacing="0">
<tbody>
<tr style="vertical-align: top;">
	<td style="padding-right: 4px;">
		<?php echo $this->__('Username')?> <input name="username" value="" type="text">
		<?php echo $this->__('Password')?> <input name="password" value="" type="password">
	</td>
</tr><tr>
	<td style="padding-right: 4px;">
		<?php echo $this->__('Remember me')?> <input name="rememberme" type="checkbox">
		<input name="submit" value="<?php echo $this->__('Log in!')?>" type="submit">
	</td>
</tr><tr>
	<td style="padding-right: 4px;">
		<a href="lostpassword.php"><?php echo $this->__('I have lost my password.')?></a>
	</td>
</tr>
</tbody>
</table>
</form>
</div>
</div>
<div id="mainmenu" style="margin-top: 20px;">
<a href="reg.php"><?php echo $this->__('Register')?></a>
<a href="<?php echo $this->getData('board_url')?>"><?php echo $this->__('Boards')?></a>
<a href="contact.php"><?php echo $this->__('Contact')?></a>
</div>
<div id="rightmenu" class="rightmenu">
<div id="title"><?php echo $this->__('Welcome on %s!', $this->escape($this->getData('server_name')))?></div>
<div id="content">
<center>
<div id="text1">
<div style="text-align: left;"><?php echo $this->__('<strong>%1$s</strong> make you an emperor. Conquer outer space and master other players on <strong>%1$s</strong>.', $this->getData('server_name'))?></div>
</div>
<div id="register" class="bigbutton" onclick="document.location.href='reg.php';"><font color="#cc0000"><?php echo $this->__('Register now!')?></font></div>
<div id="text2">
<div id="text3">
<center>
  <b>
    <font color="#00cc00"><?php echo $this->__('Player count: ')?></font><font color="#c6c7c6"><?php echo $this->getData('user_count')?></font> -
    <font color="#00cc00"><?php echo $this->__('Latest player: ')?></font><font color="#c6c7c6"><?php echo $this->getData('latest_player')?></font> -
    <font color="#00cc00"><?php echo $this->__('Online players: ')?></font> <font color="#c6c7c6"><?php echo $this->getData('online_players')?></font>
  </b>
</center>
</div>
</div>
</center>
</div>
</div>
</div>