<?php /** @var Legacies_Core_Block_Template $this */?>
<div class="item-container">
    <div class="item title">
        <h2><a href="<?php echo $this->getItemInfoUrl()?>"><?php echo $this->escape($this->getName())?></a></h2>
        <h3 class="class"><?php echo $this->__('Class %s', $this->escape($this->getClass()))?></h3>
        <h3 class="count"><?php echo $this->__('Current count: %s', $this->renderNumber($this->getQty()))?></h3>
    </div>
    <div class="item details">
        <a href="<?php echo $this->getItemInfoUrl()?>" class="image"><img src="<?php echo $this->getItemImageUrl()?>" alt="" width="120" height="120" /></a>
        <div class="qty">
            <p><input type="text" name="id[<?php echo $this->getItemId()?>]" id="ship:<?php echo $this->getItemId()?>" /></p>
            <input type="hidden" id="ship:<?php echo $this->getItemId()?>:max" value="<?php echo $this->escape($this->getMaximumBuildableElementsCount())?>" />
        </div>
        <div class="max">
            <p><a rel="ship:<?php echo $this->getItemId()?>"><?php echo $this->__('Build max (%s)', $this->renderNumber($this->getMaximumBuildableElementsCount()))?></a></p>
        </div>
        <div class="details">
            <p><?php echo $this->getDescription()?></p>
            <ul>
            <?php foreach ($this->getResourcesConfigForQty(1) as $resourceId => $resourceConfig):?>
                <li class="resource">
                    <span class="label"><?php echo $this->getResourceName($resourceId)?></span>
                    <span class="cost<?php if ($resourceConfig->hasData('requirement')):?> capped<?php endif?>"><?php echo $this->renderNumber($resourceConfig->getData('value'))?></span>
                    <?php if ($resourceConfig->hasData('requirement')):?>
                    <span class="requirement">(<?php echo $this->renderNumber($resourceConfig->getData('requirement'))?>)</span>
                    <?php else:?>
                    <span class="overflow">(<?php echo $this->renderNumber($resourceConfig->getData('overflow'))?>)</span>
                    <?php endif?>
                </li>
            <?php endforeach?>
            </ul>
            <p><?php echo $this->__('Building time: %s', $this->renderTime($this->getBuildingTime(1), false))?>
        </div>
    </div>
</div>
