<?php

namespace WootookUnit\Core\DependencyInjection;

/**
 * Test class for Wootook\Core\BaseObject.
 * Generated by PHPUnit on 2011-09-01 at 11:24:52.
 * @requires
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var \Wootook\Core\App\App
     */
    protected $_app;

    /**
     * @var \Wootook\Core\Config\Node
     */
    protected $_config;

    /**
     * @var \Wootook\Core\DependencyInjection\Registry
     */
    protected $_registry;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->_app = $this->getMock('Wootook\\Core\\App\\App', array('__construct'), array(''));
        $this->_registry = new \Wootook\Core\DependencyInjection\Registry($this->_app);
        $this->_config = new \Wootook\Core\Config\Node(array(
            'Test\\Foo' => array(
                'app'       => array('instance' => $this->_app),
                'std-class' => array('registry' => 'registry-stored-instance')
                ),
            'Test\\Bar' => null,
            'Test\\Baz' => null
            ));
    }

    public function testGetRegistryWhilePassedToConstructor()
    {
        $object = new \Wootook\Core\DependencyInjection\Factory($this->_app, $this->_config, $this->_registry);

        $this->assertAttributeSame($this->_registry, '_registry', $object);
        $this->assertSame($object->getRegistry(), $this->_registry);
    }

    public function testGetRegistryWhileNonePassedToConstructor()
    {
        $object = new \Wootook\Core\DependencyInjection\Factory($this->_app, $this->_config);

        $this->assertInstanceOf('Wootook\\Core\\DependencyInjection\\Registry', $object->getRegistry());
        $this->assertAttributeNotEmpty('_registry', $object);
        $this->assertAttributeNotSame($this->_registry, '_registry', $object);

        $object->setRegistry($this->_registry);

        $this->assertAttributeSame($this->_registry, '_registry', $object);
        $this->assertSame($object->getRegistry(), $this->_registry);
    }

    public function testGetDefinition()
    {
        $object = new \Wootook\Core\DependencyInjection\Factory($this->_app, $this->_config, $this->_registry);

        $this->assertInstanceOf('Wootook\\Core\\DependencyInjection\\Definition', $object->getDefinition('Test\\Foo'));
    }
}
