<?php

//require_once 'Wootook/Core/App/App.php';

/**
 * Test class for Wootook\Core\App.
 * Generated by PHPUnit on 2011-09-01 at 11:24:52.
 */
class WootookTest_Core_App_AppTest extends PHPUnit_Framework_TestCase
{
    protected function _getObjectMock($constructorArgs, $methods = array())
    {
        return $this->getMock('Wootook\\Core\\App\\App', $methods, $constructorArgs);
    }

    public function testConfigurationLoadingWithEnvironments()
    {
    }
}
