<div class="shipyard">
    <h1><?php echo $this->__('Shipyard')?></h1>
    <form action="<?php echo $this->getUrl('buildings.php', array('mode' => 'fleets'))?>" method="post">
        <dl>
            <?php echo $this->getPartial('item-list.items')->render()?>
        </dl>
        <input type="submit" value="<?php echo $this->__('Build')?>">
    </form>
    <script type="text/javascript">
/*<![CDATA[*/
(function($){
  $(document).ready(function(){
    $('.shipyard .buy .max').click(function(){
      $('#' + this.rel).val($('#' + this.rel + ':max').val());
      });
    });
  })(jQuery);
/*]]>*/
    </script>
</div>