<?php /** @var Wootook_Core_Block_Html_Home $this */ ?>
<?php echo $this->getLayout()->getMessagesBlock()->renderGroupedHtml()?>
<div class="home-block">
    <h1><?php echo $this->getTitle()?></h1>
    <p><?php echo $this->getFormatedWelcomeText()?></p>
    <button class="register" onclick="document.location='<?php echo $this->getUrl('player/account/new')?>'"><?php echo $this->escape('Create an empire of your own, now!')?></button>
</div>
