<?php

namespace WootookUnit\Core\App;

/**
 * Test class for Wootook\Core\App.
 * Generated by PHPUnit on 2011-09-01 at 11:24:52.
 */
class AppTest extends \PHPUnit_Framework_TestCase
{
    protected function _getObjectMock($constructorArgs, $methods = array())
    {
        return $this->getMock('Wootook\\Core\\App\\App', $methods, $constructorArgs);
    }

    public function testConfigurationLoadingWithEnvironments()
    {
    }
}
