<?php /** @var Legacies_Core_Block_Template $this */?>
<dt>
    <h2><a href="<?php echo $this->getItemInfoUrl()?>"><?php echo $this->escape($this->getName())?></a> (<?php echo $this->renderNumber($this->getLevel())?>)</h2>
</dt>
<dd>
    <a href="<?php echo $this->getItemInfoUrl()?>" class="image"><img src="<?php echo $this->getItemImageUrl()?>" alt="" width="120" height="120" /></a>
    <div class="details">
        <p><?php echo $this->getDescription()?></p>
        <ul>
        <?php foreach ($this->getResourcesNeeded() as $resourceId => $resourceValue):?>
            <li><span class="resource"><?php echo $this->getResourceName($resourceId)?></span><span class="cost"><?php echo $this->renderNumber($resourceValue)?></span></li>
        <?php endforeach?>
        </ul>
    </div>
    <div class="buy">
        <p><a class="build" href="<?php echo $this->getUrl('buildings.php', array('building' => $this->getItemId()))?>"><?php echo $this->__('Build next level (%s)', $this->renderNumber($this->getLevel() + 1))?></a></p>
    </div>
</dd>