<?php echo $this->getLayout()->getMessagesBlock()->renderGroupedHtml()?>
<form id="lost-password-form" name="lost-password-form" action="<?php echo $this->getStaticUrl('player/account/lost-password-post')?>" method="post" class="main-form">
  <fieldset>
    <legend><?php echo $this->__('Lost your password?')?></legend>
    <p class="form text">
      <label for="lost-password:username"><?php echo $this->__('Username')?></label>
      <input name="username" id="lost-password:username" value="" type="text" class="input-text" />
    </p>
    <p class="form email">
      <label for="lost-password:email"><?php echo $this->__('Email')?></label>
      <input name="email" id="lost-password:email" value="" type="text" class="input-text" />
    </p>
  </fieldset>
  <p class="form submit">
    <input id="login:submit" value="<?php echo $this->__('Send me a new password!')?>" type="submit">
  </p>
</form>
