<html>
  <head>
    <?php echo $this->head->render()?>
  </head>
  <body<?php if ($classes = $this->getBodyClasses()):?> class="<?php echo $this->escape($classes)?>"<?php endif?>>
    <div class="global">
      <div class="left">
        <?php echo $this->left->render()?>
      </div>
      <div class="content">
        <?php if (isset($this->topnav)):?>
          <?php echo $this->topnav->render()?>
        <?php endif?>
        <?php echo $this->content->render()?>
      </div>
    </div>
</body>
</html>
